# Generated by Django 6.0.5 on 2026-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('retail_price', models.BooleanField(default=True)),
                ('mrp', models.BooleanField(default=True)),
                ('b2b_price', models.BooleanField(default=True)),
                ('description', models.BooleanField(default=True)),
                ('brand', models.BooleanField(default=True)),
                ('item_code', models.BooleanField(default=True)),
                ('sku', models.BooleanField(default=True)),
                ('stock_quantity', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
