# Generated by Django 6.0.5 on 2026-05-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Category/')),
                ('quantity', models.BigIntegerField(default=0)),
                ('created_by', models.CharField(choices=[('Seller', 'Seller'), ('Admin', 'Admin'), ('Other', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('tagid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stock', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
