# Generated by Django 6.0.5 on 2026-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='category',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tagid',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Unpublish', max_length=10),
        ),
    ]
