# Generated by Django 6.0.5 on 2026-05-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userexport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExport',
        ),
    ]
