# Generated by Django 6.0.5 on 2026-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Unpublish', 'Unpublish')], default='Publish', max_length=10),
        ),
    ]
