# Generated by Django 5.1.1 on 2026-06-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
