# Generated by Django 6.0.5 on 2026-06-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_displaysetting'),
        ('home', '0021_order_orderitem'),
    ]

    operations = [
    ]
