# Generated by Django 6.0.5 on 2026-06-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_0002_displaysetting_0021_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplaySetting',
        ),
    ]
