# Generated by Django 5.1.1 on 2026-06-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_order_order_status'),
        ('home', '0023_delete_displaysetting'),
    ]

    operations = [
    ]
