# Generated by Django 5.1.1 on 2026-06-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
