# Generated by Django 5.1.1 on 2026-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_user_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
