# Generated by Django 5.1.1 on 2026-06-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_address_alternate_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.BooleanField(default=True)),
                ('retail', models.BooleanField(default=True)),
                ('b2b', models.BooleanField(default=True)),
                ('description', models.BooleanField(default=True)),
                ('brand', models.BooleanField(default=True)),
                ('item_code', models.BooleanField(default=True)),
                ('sku', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
