# Generated by Django 5.1.1 on 2026-06-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_displaysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaysetting',
            name='stock_quantity',
            field=models.BooleanField(default=True),
        ),
    ]
