# Generated by Django 5.1.1 on 2026-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('b2b', 'B2B'), ('retail', 'Retail'), ('manager', 'Manager'), ('user', 'User')], max_length=10),
        ),
    ]
